// Auto-generated by generate-presets.ts -- DO NOT EDIT
// Run: npx tsx src/lib/themes/generate-presets.ts

export type PresetMeta = {
	name: string;
	label: string;
	primaryColor: string;
	secondaryColor: string;
	primaryForegroundColor: string;
};

export const presets: readonly PresetMeta[] = [
	{
		name: 'default',
		label: 'Default',
		primaryColor: 'oklch(0.205 0 0)',
		secondaryColor: 'oklch(0.97 0 0)',
		primaryForegroundColor: 'oklch(0.985 0 0)'
	},
	{
		name: 'modern-minimal',
		label: 'Modern Minimal',
		primaryColor: 'oklch(0.6231 0.1880 259.8145)',
		secondaryColor: 'oklch(0.9670 0.0029 264.5420)',
		primaryForegroundColor: 'oklch(1.0000 0 0)'
	},
	{
		name: 'notebook',
		label: 'Notebook',
		primaryColor: 'oklch(0.4891 0 0)',
		secondaryColor: 'oklch(0.9006 0 0)',
		primaryForegroundColor: 'oklch(0.9551 0 0)'
	},
	{
		name: 'darkmatter',
		label: 'Darkmatter',
		primaryColor: 'oklch(0.6716 0.1368 48.5130)',
		secondaryColor: 'oklch(0.5360 0.0398 196.0281)',
		primaryForegroundColor: 'oklch(1.0000 0 0)'
	}
];
